#ifndef _CONSTANTS_H_
#define _CONSTANTS_H_

#define THIS_DEVICE_INTERFACE 0
#define ETHERTYPE_IP 0x0800
#define ETHERTYPE_ARP 0x0806
#define FORMER_PAYLOAD_SIZE_CPY 8
#define BROADCAST_MAC_OCTET 0xFF
#define MAC_SIZE 6
#define IPV4_SIZE 4
#define MAC_FORMAT_CODE 1
#define TYPE_ECHO_REPLY_VAL 0
#define CODE_ICMP 0
#define ETH_TYPE 1
#define ARP_REQUEST 1
#define ARP_REPLY 2
#define TYPE_DEST_UNREACH 3
#define TYPE_TIME_EXCEEDED 11
#define TTL_FULL 64
#define ARP_LEN 42
#define ICMP_LEN 98

#define MAX_RTABLE_SIZE 100000
#define MAX_ARP_TABLE_SIZE 1000

#endif